{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acm-mcp-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acm-mcp-server.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}